version: 2
registries:
  nuget_github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/oonyoen-org/index.json
    token: ${{ secrets.GITHUB_TOKEN }}
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  registries:
  - nuget_github
  reviewers:
  - "oonyoen"
